# Generated by Django 4.2.3 on 2023-08-16 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depertment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CollegeDepertment',
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('depertment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.depertment')),
            ],
            options={
                'db_table': 'CollegeDiploma',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.diploma')),
            ],
            options={
                'db_table': 'CollegeDiploma_Module',
            },
        ),
        migrations.CreateModel(
            name='Submodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='college.diploma')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.module')),
            ],
            options={
                'db_table': 'CollegeDiploma_Submodule',
            },
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_url', models.URLField()),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_diploma', to='college.diploma')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_module', to='college.module')),
                ('sub_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_submodule', to='college.submodule')),
            ],
            options={
                'db_table': 'CollegeDiploma_SubmoduleContent_VideoContent',
            },
        ),
        migrations.CreateModel(
            name='QuizContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('quiz_question_pdf', models.FileField(blank=True, null=True, upload_to='submodule_content_quiz_questions/')),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_diploma', to='college.diploma')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_module', to='college.module')),
                ('sub_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_submodule', to='college.submodule')),
            ],
            options={
                'db_table': 'CollegeDiploma_SubmoduleContent_QuizContent',
            },
        ),
        migrations.CreateModel(
            name='NoteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('notes_pdf', models.FileField(blank=True, null=True, upload_to='submodule_content_notes/')),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_diploma', to='college.diploma')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_module', to='college.module')),
                ('sub_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_submodule', to='college.submodule')),
            ],
            options={
                'db_table': 'CollegeDiploma_SubmoduleContent_notes',
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='submodule_content_images/')),
                ('exam_pdf', models.FileField(blank=True, null=True, upload_to='submodule_content_exams/')),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='CourseContent_diploma', to='college.diploma')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='CourseContent_module', to='college.module')),
                ('sub_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CourseContent_submodule', to='college.submodule')),
            ],
            options={
                'db_table': 'CollegeDiploma_SubmoduleContent',
            },
        ),
    ]
