# Generated by Django 4.2.3 on 2023-08-15 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depertment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CollegeDepertment',
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('depertment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.depertment')),
            ],
            options={
                'db_table': 'CollegeDiploma',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='submodule_images/')),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.diploma')),
            ],
            options={
                'db_table': 'CollegeDiploma_Module',
            },
        ),
        migrations.CreateModel(
            name='Submodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='submodule_banner_image/')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.module')),
            ],
            options={
                'db_table': 'CollegeDiploma_Submodule',
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='submodule_content_images/')),
                ('exam_pdf', models.FileField(blank=True, null=True, upload_to='submodule_content_exams/')),
                ('sub_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.module')),
            ],
            options={
                'db_table': 'CollegeDiploma_SubmoduleContent',
            },
        ),
    ]
