# Generated by Django 4.2.3 on 2023-08-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='image',
        ),
    ]
