# Generated by Django 4.2.3 on 2023-08-15 06:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_remove_module_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodule',
            name='diploma',
            field=models.ForeignKey(default = 1, on_delete=django.db.models.deletion.CASCADE, to='college.diploma'),
            preserve_default=False,
        ),
    ]
