# Generated by Django 4.2.3 on 2023-08-15 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_submodule_diploma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submodule',
            name='diploma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='college.diploma'),
        ),
    ]
