# Generated by Django 4.2.3 on 2023-08-15 06:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_alter_submodule_diploma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submodule',
            name='image',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='diploma',
            field=models.ForeignKey(default = 1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CourseContent_diploma', to='college.diploma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='module',
            field=models.ForeignKey(default = 1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CourseContent_module', to='college.module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='sub_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CourseContent_submodule', to='college.module'),
        ),
    ]
