# Generated by Django 4.2.3 on 2023-08-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiostation_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='RadioStationCategory',
        ),
    ]
